### ISSUE TITLE
[Issue] Reddit newsfeed remains hidden when turning eradication of

### ISSUE THREAD

**Issue by jan1577** [jordwest/news-feed-eradicator#286]
After the update, blocking works on reddit, but the feed remains hidden when turning eradication off.
The quote disappears, but there's only dividiers in the feed. Witout an adblocker, there are only sponsored posts separated by dividers and empty slots for regular posts.

On Chrome & Brave, not tested on Firefox

**Comment by valeriikundas** [comment]
hi @jordwest, I've fixed the issue and I'd appreciate adding it to the next release. thank you!

if anyone can test it on their devices, that would be useful.

**Comment by samgermain** [comment]
This issue is still happening

![](https://i.imgur.com/A2gU65c.gif)

Using 

firefox v 130.0.1 (64-bit)
MacOS Ventura 13.4.1
Apple M2 Max

**Comment by ollosh** [comment]
Yeah I can confirm the same behaviour, it seems like it always hides some content on the top

**Comment by brorbw** [comment]
Can confirm however only in the "new" reddit
